// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rps-service.proto

package com.projn.alps.rpc;

public interface GrpcRequestMsgInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.projn.alps.rpc.GrpcRequestMsgInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serviceName = 1;</code>
   */
  String getServiceName();
  /**
   * <code>string serviceName = 1;</code>
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>string requestBody = 2;</code>
   */
  String getRequestBody();
  /**
   * <code>string requestBody = 2;</code>
   */
  com.google.protobuf.ByteString
      getRequestBodyBytes();
}
