// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rps-service.proto

package com.projn.alps.rpc;

public interface GrpcResponseMsgInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.projn.alps.rpc.GrpcResponseMsgInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseBody = 1;</code>
   */
  String getResponseBody();
  /**
   * <code>string responseBody = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseBodyBytes();
}
