// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rps-service.proto

package com.projn.alps.rpc;

public final class RpsService {
  private RpsService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_projn_alps_rpc_GrpcRequestMsgInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_projn_alps_rpc_GrpcRequestMsgInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_projn_alps_rpc_GrpcResponseMsgInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_projn_alps_rpc_GrpcResponseMsgInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021rps-service.proto\022\022com.projn.alps.rpc\"" +
      ">\n\022GrpcRequestMsgInfo\022\023\n\013serviceName\030\001 \001" +
      "(\t\022\023\n\013requestBody\030\002 \001(\t\"+\n\023GrpcResponseM" +
      "sgInfo\022\024\n\014responseBody\030\001 \001(\t2k\n\013GrpcServ" +
      "ice\022\\\n\007execute\022&.com.projn.alps.rpc.Grpc" +
      "RequestMsgInfo\032\'.com.projn.alps.rpc.Grpc" +
      "ResponseMsgInfo\"\000B\026\n\022com.projn.alps.rpcP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_projn_alps_rpc_GrpcRequestMsgInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_projn_alps_rpc_GrpcRequestMsgInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_projn_alps_rpc_GrpcRequestMsgInfo_descriptor,
        new String[] { "ServiceName", "RequestBody", });
    internal_static_com_projn_alps_rpc_GrpcResponseMsgInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_projn_alps_rpc_GrpcResponseMsgInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_projn_alps_rpc_GrpcResponseMsgInfo_descriptor,
        new String[] { "ResponseBody", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
