openapi: 3.0.0
info:
  description: |
    宠到家宠物病例采集客户端，WINDOWS平台API
  version: "1.0.0"
  title: 宠到家病例采集客户端 API
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: client#http
    description: 软件相关API
  - name: user#http
    description: 用户相关API
  - name: pet#http
    description: 宠物相关API
  - name: medical#http
    description: 病例相关API
paths:
  /client/version:
    post:
      tags:
        - client#http
      summary: 检验软件版本信息
      operationId: CheckAppVersionInfo
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckAppVersionResponseInfo'
            headers:
              x-auth-token:
                description: JWT
                schema:
                  type: string
      requestBody:
        $ref: '#/components/requestBodies/CheckAppVersionRequestInfo'

  /user/verification-code:
    get:
      tags:
        - user#http
      summary: 登录验证码
      operationId: GetVerificationCodeInfo
      parameters:
        - name: x-access-token
          in: header
          description: JWT
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功，返回二进制图片信息
          content:
            application/x-plt:
              schema:
                type: string
                format: binary

  /user/login:
    post:
      tags:
        - user#http
      summary: 用户登录
      operationId: Login
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponseInfo'
            headers:
              x-auth-token:
                description: JWT
                schema:
                  type: string
      requestBody:
        $ref: '#/components/requestBodies/LoginRequestInfo'

  /user/logout:
    get:
      tags:
        - user#http
      summary: 用户注销登录
      operationId: Logout
      parameters:
        - name: x-access-token
          in: header
          description: JWT
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功

  /pet/pet-info/{pet_id}:
    get:
      tags:
        - pet#http
      summary: 获取宠物信息
      operationId: GetPetInfo
      parameters:
        - name: pet_id
          in: path
          description: 宠物ID
          required: true
          schema:
            type: string
        - name: x-access-token
          in: header
          description: JWT
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetInfoResponseInfo'

  /medical/pet-medical-info/{case_id}:
    post:
      tags:
        - medical#http
      summary: 提交宠物病例信息
      operationId: UploadPetMedicalInfo
      parameters:
        - name: case_id
          in: path
          description: 病例ID
          required: true
          schema:
            type: string
        - name: pet_id
          in: query
          description: 宠物ID
          required: true
          schema:
            type: string
        - name: customer_id
          in: query
          description: 消费者ID
          required: true
          schema:
            type: string
        - name: type
          in: query
          description: 消费者ID
          required: true
          schema:
            type: integer
            format: int32
            enum:
              - 0#FILE_TYPE_XML
              - 1#FILE_TYPE_PICTURE
            default: 0
        - name: x-access-token
          in: header
          description: JWT
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功
      requestBody:
        $ref: '#/components/requestBodies/PetMedicalRequestInfo'

  /medical/pet-medical-info-list/{pet_id}:
    get:
      tags:
        - medical#http
      summary: 获取宠物病例信息列表
      operationId: GetPetMedicalInfoList
      parameters:
        - name: pet_id
          in: path
          description: 宠物ID
          required: true
          schema:
            type: string

        - name: pageIndex
          in: query
          required: true
          schema:
            type: integer
            format: int32

        - name: pageSize
          in: query
          required: true
          schema:
            type: integer
            format: int32
            default: 10

        - name: startTime
          in: query
          required: true
          schema:
            type: integer
            format: int64

        - name: endTime
          in: query
          required: true
          schema:
            type: integer
            format: int64

        - name: x-access-token
          in: header
          description: JWT
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetMedicalInfoListResponseInfo'

externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
components:
  schemas:
    CheckAppVersionRequestInfo:
      type: object
      required:
        - deviceId
        - cpuSerialNum
        - hardDiskSerialNum
        - systemType
        - systemVersion
        - appVersion
      properties:
        deviceId:
          type: string
          description: 设备ID，由客户端生成
          example: d49b994b-9325-48d5-8c43-f451cacd5713
        deviceInfo:
          type: string
          description: 设备描述信息
        cpuSerialNum:
          type: string
          description: 设备分辨率
          example: 800*1000,1600*2000
        hardDiskSerialNum:
          type: string
          description: 设备分辨率
          example: 800*1000,1600*2000
        systemType:
          type: integer
          format: int32
          description: 系统类型
          enum:
            - 0#SYSTEM_TYPE_WINDOWS
            - 1#SYSTEM_TYPE_IOS
            - 2#SYSTEM_TYPE_ANDROID
            - 3#SYSTEM_TYPE_LINUX
        systemVersion:
          type: string
          description: 系统版本
          example: 1.0
        appVersion:
          type: string
          description: 系统版本
          example: 1.0

    CheckAppVersionResponseInfo:
      type: object
      properties:
        versionStatus:
          type: integer
          format: int32
          description: 版本状态
          enum:
            - 0 #不需要升级
            - 1 #有可用升级
            - 2 #必须升级
        updateVersion:
          type: string
          description: 升级版本
        updateUrl:
          type: string
          description: 升级包下载URL
        packetSize:
          type: integer
          format: int64
          description: 升级包尺寸
        packetMd5:
          type: string
          description: 升级MD5
        randomNum:
          type: integer
          format: int32
          description: 登录随机码

    LoginRequestInfo:
      type: object
      properties:
        account:
          type: string
          description: 账户（工号）
        key:
          type: string
          description: 密码+登录随机码+md5
        deviceId:
          type: string
          description: 设备ID
        verificationCode:
          type: string
          description: 验证码
      xml:
        name: LoginRequestInfo

    LoginResponseInfo:
      type: object
      properties:
        account:
          type: string
          description: 账户
        accountId:
          type: string
          description: 账户ID
        realName:
          type: string
          description: 姓名
        businessName:
          type: string
          description: 岗位名称
        headImage:
          type: string
          description: 头像ID
        registerTime:
          type: number
          format: int64
          description: 注册时间
      xml:
        name: LoginResponseInfo

    PetInfoResponseInfo:
      type: object
      properties:
        id:
          type: string
          description: ID
        name:
          type: string
          description: 昵称
        head_image:
          type: string
          description: 头像
        birthday:
          type: integer
          format: int64
          description: 生日
        sex:
          type: integer
          format: int32
          description: 性别
          enum:
           - 0#PET_SEX_UNKNOWN
           - 1#PET_SEX_BOY
           - 2#PET_SEX_GIRL
        breed:
          type: integer
          format: int32
          description: 大类行
        breed_name:
          type: string
          description: 大类型名
        type:
          type: integer
          format: int32
          description: 品种
        type_name:
          type: string
          description: 品种名

    PetMedicalInfoListResponseInfo:
      type: object
      properties:
        petMedicalInfoResponseInfoList:
          type: array
          items:
            $ref: '#/components/schemas/PetMedicalInfoResponseInfo'

    PetMedicalInfoResponseInfo:
      type: object
      properties:
        id:
          type: string
          description: 编号
        summary:
          type: string
          description: 摘要
        recordTime:
          type: integer
          format: int32
          description: 记录时间
        caseName:
          type: string
          description: 病例名


  requestBodies:
    CheckAppVersionRequestInfo:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CheckAppVersionRequestInfo'
      description: 检验软件版本信息结构
      required: true

    LoginRequestInfo:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LoginRequestInfo'
      description: 用户登录结构
      required: true

    PetMedicalRequestInfo:
      content:
        application/file:
          schema:
            type: string
            format: binary
      description: 宠物病例信息
      required: true
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/sunyuecheng/HomePetsCare-COLLECTOR/1.0.0